## Generate and insert into each table

Before executing the code, make sure that the Database exists!

In [1]:
!pip install mysql-connector-python faker

Requirement already satisfied: mysql-connector-python in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (9.3.0)
Requirement already satisfied: faker in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (37.4.0)
Requirement already satisfied: tzdata in c:\users\user\appdata\local\programs\python\python313\lib\site-packages (from faker) (2025.2)

[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

#### Create table and insert into User

In [8]:
import random
import string
import mysql.connector  # Replace with your database connector library (e.g., psycopg2 for PostgreSQL)
from faker import Faker
from datetime import datetime

faker = Faker();

# Database connection details (replace with your credentials)
DB_HOST = "localhost"
DB_USER = "root"
DB_PASSWORD = ""
DB_NAME = "test_database"  # Replace with your database name

# Function to generate random data (you can customize this)
def generate_user_data():
  roles = ['admin', 'staff', 'customer']
  name = faker.name()
  email = faker.email()
  password = faker.password()
  role = random.choice(roles)
  created_at = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
  return name, email, password, role, created_at

# Connect to the database
try:
    connection = mysql.connector.connect(host=DB_HOST, user=DB_USER, password=DB_PASSWORD, database=DB_NAME)
    cursor = connection.cursor()
except mysql.connector.Error as err:
  print("Error connecting to database:", err)
  exit()

# Create table from file ---------------------------------------

# Open and read the file as a single buffer
fd = open('../Database_Implementation/Project_script.sql', 'r')
sqlFile = fd.read()
fd.close()

# all SQL commands (split on ';')
sqlCommands = sqlFile.split(';')

# Execute every command from the input file
for command in sqlCommands:
  if command.__len__() > 10: # Filter out the empty string
    cursor.execute(command)
connection.commit()

# Done creating tables -----------------------------------------

# Generate and insert data
print('Start inserting ...')
insertion_amount = 10
num_records = 1000000
i = 0
for k in range(insertion_amount):
  for _ in range(num_records):
    name, email, password, role, created_at = generate_user_data()
    insert_query = """
    INSERT INTO User (name, email, password, role, created_at)
    VALUES (%s, %s, %s, %s, %s)
    """
    cursor.execute(insert_query, (name, email, password, role, created_at))
  connection.commit()
  i = i + 1
  print('Insertion round', i, num_records, 'records.')

print(f"Successfully inserted {num_records*insertion_amount} records into the database.")

# Close the connection
cursor.close()
connection.close()

print('Finished inserting!!!')

Start inserting ...

KeyboardInterrupt:

#### Generate stock

In [ ]:
import random
import mysql.connector
from datetime import datetime

# Database connection details (replace with your credentials)
DB_HOST = "localhost"
DB_USER = "root"
DB_PASSWORD = ""
DB_NAME = "test_database"

# Function to generate random data (you can customize this)
def generate_stock_data(var):
  variant_id = var
  qty = random.randint(1, 1000)
  type = random.choice(['in', 'out'])
  created_at = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
  return variant_id, qty, type, created_at

# Connect to the database
try:
    connection = mysql.connector.connect(host=DB_HOST, user=DB_USER, password=DB_PASSWORD, database=DB_NAME)
    cursor = connection.cursor()
except mysql.connector.Error as err:
  print("Error connecting to database:", err)
  exit()

# Generate and insert data
MAX_STOCK_PER_VARIANT = 3

cursor.execute('SELECT id FROM Product_Variant ORDER BY id ASC')
fetched_ids = cursor.fetchall()
variant_ids = [row[0] for row in fetched_ids]
total_variant = len(variant_ids)
print('Amount of product variant: ', len(fetched_ids))

if not variant_ids:
  print("No variant IDs found or fetched. Cannot generate stocks. Exiting.")
  exit

print('Start inserting ...')
i = 0
total_record = 0
for k in range(total_variant):
  stocking = random.randint(1, MAX_STOCK_PER_VARIANT)
  for _ in range(stocking):
    variant_id, qty, type, created_at = generate_stock_data(variant_ids[k])
    insert_query = """
    INSERT INTO Stock_Transaction (variant_id, qty, type, created_at)
    VALUES (%s, %s, %s, %s)
    """
    cursor.execute(insert_query, (variant_id, qty, type, created_at))
  connection.commit()
  i = i + 1
  print('Insertion variant', i, stocking, 'records.')
  total_record += stocking

print(f"Successfully inserted {total_record} records into the database.")

# Close the connection
cursor.close()
connection.close()

print('Finished inserting!!!')

Amount of product variant:  315
Start inserting ...
Insertion variant 1 3 records.
Insertion variant 2 1 records.
Insertion variant 3 2 records.
Insertion variant 4 3 records.
Insertion variant 5 1 records.
Insertion variant 6 2 records.
Insertion variant 7 2 records.
Insertion variant 8 1 records.
Insertion variant 9 2 records.
Insertion variant 10 1 records.
Insertion variant 11 3 records.
Insertion variant 12 2 records.
Insertion variant 13 3 records.
Insertion variant 14 1 records.
Insertion variant 15 2 records.
Insertion variant 16 2 records.
Insertion variant 17 2 records.
Insertion variant 18 3 records.
Insertion variant 19 3 records.
Insertion variant 20 1 records.
Insertion variant 21 3 records.
Insertion variant 22 2 records.
Insertion variant 23 3 records.
Insertion variant 24 1 records.
Insertion variant 25 1 records.
Insertion variant 26 1 records.
Insertion variant 27 3 records.
Insertion variant 28 1 records.
Insertion variant 29 1 records.
Insertion variant 30 3 records.
Insertion variant 31 2 records.
Insertion variant 32 1 records.
Insertion variant 33 1 records.
Insertion variant 34 1 records.
Insertion variant 35 2 records.
Insertion variant 36 3 records.
Insertion variant 37 1 records.
Insertion variant 38 3 records.
Insertion variant 39 1 records.
Insertion variant 40 1 records.
Insertion variant 41 2 records.
Insertion variant 42 1 records.
Insertion variant 43 1 records.
Insertion variant 44 1 records.
Insertion variant 45 2 records.
Insertion variant 46 3 records.
Insertion variant 47 2 records.
Insertion variant 48 1 records.
Insertion variant 49 1 records.
Insertion variant 50 2 records.
Insertion variant 51 2 records.
Insertion variant 52 2 records.
Insertion variant 53 2 records.
Insertion variant 54 2 records.
Insertion variant 55 3 records.
Insertion variant 56 1 records.
Insertion variant 57 1 records.
Insertion variant 58 3 records.
Insertion variant 59 2 records.
Insertion variant 60 2 records.
Insertion variant 61 3 records.
Insertion variant 62 2 records.
Insertion variant 63 1 records.
Insertion variant 64 1 records.
Insertion variant 65 2 records.
Insertion variant 66 2 records.
Insertion variant 67 2 records.
Insertion variant 68 1 records.
Insertion variant 69 1 records.
Insertion variant 70 1 records.
Insertion variant 71 1 records.
Insertion variant 72 3 records.
Insertion variant 73 3 records.
Insertion variant 74 2 records.
Insertion variant 75 3 records.
Insertion variant 76 2 records.
Insertion variant 77 1 records.
Insertion variant 78 2 records.
Insertion variant 79 2 records.
Insertion variant 80 2 records.
Insertion variant 81 3 records.
Insertion variant 82 1 records.
Insertion variant 83 2 records.
Insertion variant 84 1 records.
Insertion variant 85 1 records.
Insertion variant 86 3 records.
Insertion variant 87 1 records.
Insertion variant 88 1 records.
Insertion variant 89 3 records.
Insertion variant 90 3 records.
Insertion variant 91 1 records.
Insertion variant 92 3 records.
Insertion variant 93 1 records.
Insertion variant 94 1 records.
Insertion variant 95 3 records.
Insertion variant 96 3 records.
Insertion variant 97 3 records.
Insertion variant 98 2 records.
Insertion variant 99 2 records.
Insertion variant 100 1 records.
Insertion variant 101 2 records.
Insertion variant 102 2 records.
Insertion variant 103 1 records.
Insertion variant 104 1 records.
Insertion variant 105 1 records.
Insertion variant 106 1 records.
Insertion variant 107 1 records.
Insertion variant 108 3 records.
Insertion variant 109 3 records.
Insertion variant 110 3 records.
Insertion variant 111 3 records.
Insertion variant 112 1 records.
Insertion variant 113 1 records.
Insertion variant 114 1 records.
Insertion variant 115 3 records.
Insertion variant 116 1 records.
Insertion variant 117 3 records.
Insertion variant 118 1 records.
Insertion variant 119 3 records.
Insertion variant 120 1 records.
Insertion variant 121 3 records.
Insertion variant 122 1 records.
Insertion variant 123 3 records.
Insertion variant 124 3 records.
Insertion variant 125 2 records.
Insertion variant 126 1 records.
Insertion variant 127 1 records.
Insertion variant 128 2 records.
Insertion variant 129 2 records.
Insertion variant 130 2 records.
Insertion variant 131 1 records.
Insertion variant 132 3 records.
Insertion variant 133 3 records.
Insertion variant 134 2 records.
Insertion variant 135 1 records.
Insertion variant 136 2 records.
Insertion variant 137 2 records.
Insertion variant 138 2 records.
Insertion variant 139 3 records.
Insertion variant 140 1 records.
Insertion variant 141 1 records.
Insertion variant 142 1 records.
Insertion variant 143 3 records.
Insertion variant 144 2 records.
Insertion variant 145 2 records.
Insertion variant 146 2 records.
Insertion variant 147 1 records.
Insertion variant 148 2 records.
Insertion variant 149 3 records.
Insertion variant 150 1 records.
Insertion variant 151 1 records.
Insertion variant 152 3 records.
Insertion variant 153 2 records.
Insertion variant 154 1 records.
Insertion variant 155 3 records.
Insertion variant 156 1 records.
Insertion variant 157 3 records.
Insertion variant 158 2 records.
Insertion variant 159 3 records.
Insertion variant 160 2 records.
Insertion variant 161 3 records.
Insertion variant 162 3 records.
Insertion variant 163 2 records.
Insertion variant 164 3 records.
Insertion variant 165 2 records.
Insertion variant 166 2 records.
Insertion variant 167 3 records.
Insertion variant 168 3 records.
Insertion variant 169 3 records.
Insertion variant 170 2 records.
Insertion variant 171 1 records.
Insertion variant 172 1 records.
Insertion variant 173 1 records.
Insertion variant 174 2 records.
Insertion variant 175 1 records.
Insertion variant 176 3 records.
Insertion variant 177 2 records.
Insertion variant 178 1 records.
Insertion variant 179 3 records.
Insertion variant 180 1 records.
Insertion variant 181 3 records.
Insertion variant 182 1 records.
Insertion variant 183 3 records.
Insertion variant 184 2 records.
Insertion variant 185 2 records.
Insertion variant 186 1 records.
Insertion variant 187 3 records.
Insertion variant 188 3 records.
Insertion variant 189 3 records.
Insertion variant 190 2 records.
Insertion variant 191 2 records.
Insertion variant 192 1 records.
Insertion variant 193 1 records.
Insertion variant 194 2 records.
Insertion variant 195 3 records.
Insertion variant 196 2 records.
Insertion variant 197 3 records.
Insertion variant 198 3 records.
Insertion variant 199 2 records.
Insertion variant 200 1 records.
Insertion variant 201 3 records.
Insertion variant 202 3 records.
Insertion variant 203 2 records.
Insertion variant 204 3 records.
Insertion variant 205 2 records.
Insertion variant 206 1 records.
Insertion variant 207 2 records.
Insertion variant 208 1 records.
Insertion variant 209 1 records.
Insertion variant 210 3 records.
Insertion variant 211 2 records.
Insertion variant 212 3 records.
Insertion variant 213 1 records.
Insertion variant 214 1 records.
Insertion variant 215 1 records.
Insertion variant 216 3 records.
Insertion variant 217 1 records.
Insertion variant 218 1 records.
Insertion variant 219 2 records.
Insertion variant 220 1 records.
Insertion variant 221 3 records.
Insertion variant 222 1 records.
Insertion variant 223 1 records.
Insertion variant 224 2 records.
Insertion variant 225 1 records.
Insertion variant 226 3 records.
Insertion variant 227 2 records.
Insertion variant 228 1 records.
Insertion variant 229 2 records.
Insertion variant 230 3 records.
Insertion variant 231 3 records.
Insertion variant 232 1 records.
Insertion variant 233 2 records.
Insertion variant 234 2 records.
Insertion variant 235 1 records.
Insertion variant 236 3 records.
Insertion variant 237 1 records.
Insertion variant 238 2 records.
Insertion variant 239 3 records.
Insertion variant 240 1 records.
Insertion variant 241 2 records.
Insertion variant 242 1 records.
Insertion variant 243 3 records.
Insertion variant 244 1 records.
Insertion variant 245 2 records.
Insertion variant 246 1 records.
Insertion variant 247 2 records.
Insertion variant 248 2 records.
Insertion variant 249 1 records.
Insertion variant 250 1 records.
Insertion variant 251 2 records.
Insertion variant 252 2 records.
Insertion variant 253 3 records.
Insertion variant 254 1 records.
Insertion variant 255 1 records.
Insertion variant 256 3 records.
Insertion variant 257 2 records.
Insertion variant 258 3 records.
Insertion variant 259 3 records.
Insertion variant 260 1 records.
Insertion variant 261 2 records.
Insertion variant 262 3 records.
Insertion variant 263 1 records.
Insertion variant 264 1 records.
Insertion variant 265 1 records.
Insertion variant 266 3 records.
Insertion variant 267 2 records.
Insertion variant 268 1 records.
Insertion variant 269 2 records.
Insertion variant 270 2 records.
Insertion variant 271 2 records.
Insertion variant 272 3 records.
Insertion variant 273 2 records.
Insertion variant 274 3 records.
Insertion variant 275 2 records.
Insertion variant 276 1 records.
Insertion variant 277 1 records.
Insertion variant 278 1 records.
Insertion variant 279 1 records.
Insertion variant 280 2 records.
Insertion variant 281 3 records.
Insertion variant 282 3 records.
Insertion variant 283 3 records.
Insertion variant 284 1 records.
Insertion variant 285 1 records.
Insertion variant 286 1 records.
Insertion variant 287 1 records.
Insertion variant 288 1 records.
Insertion variant 289 3 records.
Insertion variant 290 3 records.
Insertion variant 291 2 records.
Insertion variant 292 1 records.
Insertion variant 293 1 records.
Insertion variant 294 2 records.
Insertion variant 295 3 records.
Insertion variant 296 2 records.
Insertion variant 297 3 records.
Insertion variant 298 3 records.
Insertion variant 299 1 records.
Insertion variant 300 2 records.
Insertion variant 301 3 records.
Insertion variant 302 2 records.
Insertion variant 303 3 records.
Insertion variant 304 1 records.
Insertion variant 305 3 records.
Insertion variant 306 2 records.
Insertion variant 307 3 records.
Insertion variant 308 1 records.
Insertion variant 309 1 records.
Insertion variant 310 3 records.
Insertion variant 311 2 records.
Insertion variant 312 3 records.
Insertion variant 313 2 records.
Insertion variant 314 2 records.
Insertion variant 315 3 records.
Successfully inserted 609 records into the database.
Finished inserting!!!